### ISSUE TITLE
ValueError when running test peak files

### ISSUE THREAD

**Issue by doliv071** [nboley/idr#34]
Hi, I'm running idr-2.0.2 in a virtual environment installed with python3.6 and I'm getting the following error running the test command (I also got this error on a real dataset).

Could this be a specific issue with running in a virtual environment?

Thanks,
-Dave

```
(IDR) [oliverd@aphrodite bin]$ idr --samples ../tests/data/peak1 ../tests/data/peak1
Initial parameter values: [0.10 1.00 0.20 0.50]
Final parameter values: [0.05 0.20 0.99 0.99]
/athena/hssgenomics/scratch/programs/IDR/bin/idr --samples ../tests/data/peak1 ../tests/data/peak1
Traceback (most recent call last):
  File "/athena/hssgenomics/scratch/programs/IDR/bin/idr", line 4, in <module>
    __import__('pkg_resources').run_script('idr==2.0.2', 'idr')
  File "/athena/hssgenomics/scratch/programs/IDR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 739, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/athena/hssgenomics/scratch/programs/IDR/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1500, in run_script
    exec(code, namespace, namespace)
  File "/athena/hssgenomics/scratch/programs/IDR/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/idr", line 10, in <module>
    idr.idr.main()
  File "/athena/hssgenomics/scratch/programs/IDR/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/idr/idr.py", line 774, in main
    useBackwardsCompatibleOutput=args.use_old_output_format)
  File "/athena/hssgenomics/scratch/programs/IDR/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/idr/idr.py", line 415, in write_results_to_file
    if localIDRs == None or IDRs == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

**Comment by P4sm** [comment]
I had the same issue when I installed idr by:
`python3 setup.py install`
where python3 was Python3.5 already on my system.
and tried the test run and got the error, but then I installed Anaconda and installed it again and the problem disappeared.

`Download [Anaconda3-2.2.0-Linux-x86_64.sh](http://continuum.io/downloads#py34)`
`bash Anaconda3-2.2.0-Linux-x86_64.sh`

And I didn't use it in a virtual environment.

**Comment by parashardhapola** [comment]
I get the same error:

```
Initial parameter values: [0.10 1.00 0.20 0.50]
Final parameter values: [1.22 0.76 0.60 0.49]
/home/parashar/anaconda3/bin/idr --rank p.value --input-file-type narrowPeak --samples macs_peaks/S1_peaks.narrowPeak macs_peaks/S3_peaks.narrowPeak --output-file IDR_analysis/S1_S3
Traceback (most recent call last):
  File "/home/parashar/anaconda3/bin/idr", line 4, in <module>
    __import__('pkg_resources').run_script('idr==2.0.2', 'idr')
  File "/home/parashar/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 744, in run_script
  File "/home/parashar/anaconda3/lib/python3.6/site-packages/setuptools-27.2.0-py3.6.egg/pkg_resources/__init__.py", line 1499, in run_script
  File "/home/parashar/anaconda3/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/EGG-INFO/scripts/idr", line 10, in <module>
    idr.idr.main()
  File "/home/parashar/anaconda3/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/idr/idr.py", line 774, in main
    useBackwardsCompatibleOutput=args.use_old_output_format)
  File "/home/parashar/anaconda3/lib/python3.6/site-packages/idr-2.0.2-py3.6-linux-x86_64.egg/idr/idr.py", line 415, in write_results_to_file
    if localIDRs == None or IDRs == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()
```

My Python version is:
Python 3.6.2 :: Anaconda custom (64-bit)
Have installed Anaconda 4.4.0 on Linux.

What Python version does Anaconda3-2.2.0 contain? Maybe we can install that a conda env for that version rather than a fresh install of older Anaconda version. Can we patch this code to be compatible across versions?

**Comment by parashardhapola** [comment]
Well installed idr version 2.0.3 and it works straight out of the box with my Anaconda version containing Python 3.6.2

**Comment by doliv071** [comment]
2.0.3 fixed this error for me as well.

**Comment by Fenglingli** [comment]
根据您提供的错误信息，看起来这个问题是由于在代码中对于数组类型的变量判断真值时出现了歧义。要解决这个问题，您可以按照下面的步骤进行处理：打开 /home/.../anaconda3/lib/python3.9/site-packages/idr-2.0.2-py3.9-linux-x86_64.egg/idr/idr.py 文件。

找到报错的那一行代码，即第415行：

 if localIDRs == None or IDRs == None:
Copy
将这一行代码修改为：
if localIDRs is None or IDRs is None:

保存文件并重新运行您的命令即可。
