### ISSUE TITLE
idr error with narrowPeaks

### ISSUE THREAD

**Issue by wisense** [nboley/idr#39]
Hi,
I run idr with the test narrowPeaks files and my own narrowPeaks files. They all ended up with an error:

[wszheng@guru idr-2.0.2]$ idr --samples tests/data/peak1 tests/data/peak2 
WARNING: Cython does not appear to be installed.- falling back to much slower python method.
Initial parameter values: [0.10 1.00 0.20 0.50]
/home/wszheng/Install/Python-3.6.1/bin/idr --samples tests/data/peak1 tests/data/peak2
Traceback (most recent call last):
  File "/home/wszheng/Install/Python-3.6.1/bin/idr", line 4, in <module>
    __import__('pkg_resources').run_script('idr==2.0.2', 'idr')
  File "/home/wszheng/Install/Python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 654, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/home/wszheng/Install/Python-3.6.1/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1434, in run_script
    exec(code, namespace, namespace)
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr.egg-info/scripts/idr", line 10, in <module>
    idr.idr.main()
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr/idr.py", line 759, in main
    fix_mu=args.fix_mu, fix_sigma=args.fix_sigma )    
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr/idr.py", line 391, in fit_model_and_calc_idr
    fix_mu=fix_mu, fix_sigma=fix_sigma)
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr/optimization.py", line 468, in estimate_model_params
    fix_mu=fix_mu, fix_sigma=fix_sigma)
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr/optimization.py", line 420, in EMP_with_pseudo_value_algorithm
    z1 = compute_pseudo_values(r1, theta[0], theta[1], theta[3])
  File "/home/wszheng/Install/Source_binaries/idr-2.0.2/idr/utility.py", line 46, in py_compute_pseudo_values
    -10, 10, EPS ) )
TypeError: py_cdf_i() takes 6 positional arguments but 7 were given

Can anyone help me figure out this problem? Thanks very much.

**Comment by dcdxy** [comment]
@wisense Were you able to find a solution for this? I am experiencing the same issue.

**Comment by rcwchan** [comment]
Hi,

I received this error and a variety of others (to do with numpy, cython, matplotlib, the error referenced in #34 ) and ultimately got it to work by using the idr provided on bioconda. I created the following conda environment:

`conda create --name idr_filtering python=3.6 cython numpy matplotlib scipy libgfortran idr`

and it seemed to run after that. Hopefully this is helpful to someone.
