### ISSUE TITLE
IndexError: list index out of range

### ISSUE THREAD

**Issue by aparnasing** [nboley/idr#41]
Hi, I am using idr to process 2 replicate bed files but getting an index error. copying command and bash response
 idr --samples dyadvscolrep1_c3.0_common.bed dyadvscolrep2_c3.0_common.bed
/usr/local/bin/idr --samples dyadvscolrep1_c3.0_common.bed dyadvscolrep2_c3.0_common.bed
Traceback (most recent call last):
  File "/usr/local/bin/idr", line 4, in <module>
    __import__('pkg_resources').run_script('idr==2.0.3', 'idr')
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 743, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/usr/local/lib/python3.6/site-packages/pkg_resources/__init__.py", line 1498, in run_script
    exec(code, namespace, namespace)
  File "/usr/local/lib/python3.6/site-packages/idr-2.0.3-py3.6-linux-x86_64.egg/EGG-INFO/scripts/idr", line 10, in <module>
    idr.idr.main()
  File "/usr/local/lib/python3.6/site-packages/idr-2.0.3-py3.6-linux-x86_64.egg/idr/idr.py", line 839, in main
    merged_peaks, signal_type = load_samples(args)
  File "/usr/local/lib/python3.6/site-packages/idr-2.0.3-py3.6-linux-x86_64.egg/idr/idr.py", line 703, in load_samples
    for fp in args.samples]
  File "/usr/local/lib/python3.6/site-packages/idr-2.0.3-py3.6-linux-x86_64.egg/idr/idr.py", line 703, in <listcomp>
    for fp in args.samples]
  File "/usr/local/lib/python3.6/site-packages/idr-2.0.3-py3.6-linux-x86_64.egg/idr/idr.py", line 53, in load_bed
    signal = float(data[signal_index])
IndexError: list index out of range

**Comment by melnuesch** [comment]
I got a similar error. Any thoughts?

Traceback (most recent call last):
  File "/Users/nueschm/miniconda3/bin/idr", line 4, in <module>
    __import__('pkg_resources').run_script('idr==2.0.2', 'idr')
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 666, in run_script
    self.require(requires)[0].run_script(script_name, ns)
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/pkg_resources/__init__.py", line 1453, in run_script
    exec(code, namespace, namespace)
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/idr-2.0.2-py3.7-macosx-10.7-x86_64.egg/EGG-INFO/scripts/idr", line 10, in <module>
    idr.idr.main()
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/idr-2.0.2-py3.7-macosx-10.7-x86_64.egg/idr/idr.py", line 733, in main
    merged_peaks, signal_type = load_samples(args)
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/idr-2.0.2-py3.7-macosx-10.7-x86_64.egg/idr/idr.py", line 620, in load_samples
    for fp in args.samples]
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/idr-2.0.2-py3.7-macosx-10.7-x86_64.egg/idr/idr.py", line 620, in <listcomp>
    for fp in args.samples]
  File "/Users/nueschm/miniconda3/lib/python3.7/site-packages/idr-2.0.2-py3.7-macosx-10.7-x86_64.egg/idr/idr.py", line 39, in load_bed
    if peak_summit_index == None or int(data[peak_summit_index]) == -1:
IndexError: list index out of range

**Comment by hjames1** [comment]
I got a similar error,too.

Traceback (most recent call last):
  File "/home/u100395/workdir/miniconda3/envs/chipseq/bin/idr", line 10, in <module>
    idr.idr.main()
  File "/home/u100395/workdir/miniconda3/envs/chipseq/lib/python3.7/site-packages/idr/idr.py", line 840, in main
    merged_peaks, signal_type = load_samples(args)
  File "/home/u100395/workdir/miniconda3/envs/chipseq/lib/python3.7/site-packages/idr/idr.py", line 732, in load_samples
    f1, f2 = [load_bed(fp, signal_index) for fp in args.samples]
  File "/home/u100395/workdir/miniconda3/envs/chipseq/lib/python3.7/site-packages/idr/idr.py", line 732, in <listcomp>
    f1, f2 = [load_bed(fp, signal_index) for fp in args.samples]
  File "/home/u100395/workdir/miniconda3/envs/chipseq/lib/python3.7/site-packages/idr/idr.py", line 65, in load_bed
    float(data[6]), float(data[7]), float(data[8])
IndexError: list index out of range

**Comment by yx-xu** [comment]
Hello!
      I got an error same to this, but I couldn't resolve it. Have you solved the problem? Could you help me about this? Thank you very much!
     Looking forward to your reply!

**Comment by karl1926** [comment]
I had a similar issue. Any news?

**Comment by ShuZhang0917** [comment]
I had a similar error. 
  File "/storage/xx/software/miniconda3/lib/python3.9/site-packages/idr-2.0.2-py3.9-linux-x86_64.egg/idr/idr.py", line 45, in load_bed
    peak = Peak(data[0], data[5], 
IndexError: list index out of range
  File "/storage/xx/software/miniconda3/lib/python3.9/site-packages/idr-2.0.2-py3.9-linux-x86_64.egg/idr/idr.py", line 45, in load_bed
    peak = Peak(data[0], data[5], 
IndexError: list index out of range

Peak score is in the column 5th. In python, actual index is equal to py_index+1. So I set peak = Peak(data[0], data[4] in line 45 of idr.py. This error disappeared.

**Comment by brottodb** [comment]
I am having a similar problem. Anyone was able to solve this issue? Thanks!

**Comment by luorongxin-yuan** [comment]
had similar problem at line 65 when my input bed file is 8 columns, but 9 is expected. So I just kept the original 6 columns, and filled column 7-9 with 0s. Seemed to solve the problem, hopefully not interfering with statistics
File "/home/u100395/workdir/miniconda3/envs/chipseq/lib/python3.7/site-packages/idr/idr.py", line 65, in load_bed
float(data[6]), float(data[7]), float(data[8])
IndexError: list index out of range
