### ISSUE TITLE
Fails with ValueError on narrow peaks

### ISSUE THREAD

**Issue by balwierz** [nboley/idr#44]
My files are simple MACS2 narrowPeak. idr fails on these. There is an empty "idrValues.txt" file created

```
$ idr --samples s1.narrowPeak s2.narrowPeak 
Initial parameter values: [0.10 1.00 0.20 0.50]
Final parameter values: [1.99 1.40 0.91 0.57]
idr --samples s1.narrowPeak s2.narrowPeak 

Traceback (most recent call last):
  File "idr", line 10, in <module>
    idr.idr.main()
  File "idr.py", line 774, in main
    useBackwardsCompatibleOutput=args.use_old_output_format)
  File "idr.py", line 415, in write_results_to_file
    if localIDRs == None or IDRs == None:
ValueError: The truth value of an array with more than one element is ambiguous. Use a.any() or a.all()


$ python3 --version
Python 3.7.2+

```

**Comment by balwierz** [comment]
When I updated to version 2.0.3 the problem disappeared. But the installation instructions are giving an url to an old version and documentation of the new version... Closing this but and opening a documentation one.
